### ISSUE TITLE
Cannot create mount the RAM disk

### ISSUE THREAD

**Issue by noushadali** [ScriptedAlchemy/jetbrains-ide-performance#2]
Hello When i run the code, I get the following error

{code}
$ /usr/local/bin/startupRAMDiskandCacheMover.sh
++ sysctl hw.memsize
++ awk '{print $2;}'
+ ramfs_size_mb=17179869184
+ ramfs_size_mb=4096
+ mount_point=/Users/Noushad.Ali/ramdisk
+ ramfs_size_sectors=8388608
++ hdid -nomount ram://8388608
++ xargs
+ ramdisk_device=/dev/disk3
+ USERRAMDISK=/Users/Noushad.Ali/ramdisk
+ MSG_MOVE_CACHE='. Do you want me to move its cache? Note: It will close the app.'
+ MSG_PROMPT_FOUND='I found '
+ main
+ check_requirements
+ hash rsync
+ hash newfs_hfs
+ mk_ram_disk
+ umount -f /Users/Noushad.Ali/ramdisk
umount: /Users/Noushad.Ali/ramdisk: not currently mounted
+ newfs_hfs -v ramdisk /dev/disk3
Initialized /dev/rdisk3 as a 4 GB case-insensitive HFS Plus volume
+ mkdir -p /Users/Noushad.Ali/ramdisk
+ mount -o noatime -t hfs /dev/disk3 /Users/Noushad.Ali/ramdisk
mount_hfs: error on mount(): error = -1. <--- Error here 
mount_hfs: Unknown error: -16 <--- Error here 
+ echo 'created RAM disk.'
created RAM disk.
+ hide_ramdisk
+ /usr/bin/chflags hidden /Users/Noushad.Ali/ramdisk
+ echo 'RAM disk hidden'
RAM disk hidden
+ move_ideace_cache
+ '[' -d '/Applications/IntelliJ IDEA CE.app' ']'
+ user_response 'I found ' 'IntelliJ IDEA CE. Do you want me to move its cache? Note: It will close the app.'
+ echo -ne 'I found ' 'IntelliJ IDEA CE. Do you want me to move its cache? Note: It will close the app.' '[Y/n] '
I found IntelliJ IDEA CE. Do you want me to move its cache? Note: It will close the app. [Y/n] + read -r response
y
+ case ${response} in
+ true
+ close_app 'IntelliJ Idea CE'
+ osascript -e 'quit app "IntelliJ Idea CE"'
+ cp -f '/Applications/IntelliJ IDEA CE.app/Contents/bin/idea.properties' '/Applications/IntelliJ IDEA CE.app/Contents/bin/idea.properties.back'
+ echo idea.system.path=/Users/Noushad.Ali/ramdisk/Idea
+ echo idea.log.path=/Users/Noushad.Ali/ramdisk/Idea/logs
+ echo 'Moved IntelliJ cache.'
Moved IntelliJ cache.
+ create intermediate folder for intellij projects output
/usr/local/bin/startupRAMDiskandCacheMover.sh: line 366: create: command not found
+ create_intermediate_folder_for_intellij_projects
+ '[' -d /Volumes/ramdisk/Noushad.Ali/compileroutput ']'
+ mkdir -p /Volumes/ramdisk/Noushad.Ali/compileroutput
mkdir: /Volumes/ramdisk/Noushad.Ali/compileroutput: Permission denied
+ echo 'echo use "/Users/Noushad.Ali/ramdisk/compileroutput" for intelliJ project output directory.'
echo use "/Users/Noushad.Ali/ramdisk/compileroutput" for intelliJ project output directory.
+ echo 'All good - I have done my job. Your apps should fly.'
All good - I have done my job. Your apps should fly. {code}

**Comment by ScriptedAlchemy** [comment]
Log bug with origin owner of ram disk generation
